apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-balancer-example
  name: hello-world
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-balancer-example
  template:
    metadata:
      labels:
        app: load-balancer-example
    spec:
      containers:
        - image: daern91/hapi-example
          name: hello-world
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
